import {mkdir,readFile,writeFile,rename,stat} from 'node:fs/promises';
import path from 'node:path';
const valid=id=>typeof id==='string'&&/^[\w-]{1,200}$/.test(id);
export function pickActions(list){if(!Array.isArray(list))throw new Error('动作列表格式错误');return ['idle','walk','wave'].map(kind=>{const patterns={idle:/^idle$|standing.*idle|idle.*standing/i,walk:/^walking$|^walk$|walking.*forward/i,wave:/^waving$|^wave$|waving.*hand|greeting/i};const hit=list.find(x=>patterns[kind].test(x.name));if(!hit||!Number.isInteger(hit.action_id))throw new Error(`动作库中未找到 ${kind} 动作，请检查服务商目录`);return {kind,id:hit.action_id,name:hit.name}})}
export function createCharacterProvider(directory,request=fetch){const locks=new Map();
 async function call(route,payload){const r=await request('https://api.meshy.ai/openapi/v1/'+route,{method:payload?'POST':'GET',headers:{Authorization:`Bearer ${process.env.MESHY_API_KEY}`,'Content-Type':'application/json'},...(payload?{body:JSON.stringify(payload)}:{}),signal:AbortSignal.timeout(90000)});if(!r.ok)throw new Error(`人物生成服务返回 ${r.status}，请检查配置与额度`);return r.json()}
 async function save(job){await mkdir(directory,{recursive:true});const file=path.join(directory,'character-'+job.id+'.json');await writeFile(file+'.tmp',JSON.stringify(job));await rename(file+'.tmp',file)}
 async function read(id){if(!valid(id))throw new Error('无效人物任务');return JSON.parse(await readFile(path.join(directory,'character-'+id+'.json'),'utf8'))}
 async function asset(url,name){if(!url||new URL(url).protocol!=='https:')throw new Error('人物生成服务未返回有效模型');const file=path.join(directory,'assets',name);try{await stat(file);return '/assets/'+name}catch{}const r=await request(url,{signal:AbortSignal.timeout(180000)});if(!r.ok)throw new Error('人物模型下载失败');const chunks=[];let total=0;for await(const part of r.body){total+=part.length;if(total>200*1024*1024)throw new Error('人物资源超过 200 MB');chunks.push(part)}await mkdir(path.dirname(file),{recursive:true});await writeFile(file+'.tmp',Buffer.concat(chunks));await rename(file+'.tmp',file);return '/assets/'+name}
 return {async create(image){if(!process.env.MESHY_API_KEY)throw new Error('网站尚未启用人物重建服务');if(typeof image!=='string'||!/^data:image\/(png|jpeg);base64,[A-Za-z0-9+/=]+$/.test(image)||image.length>10*1024*1024)throw new Error('人物图片格式错误');const result=await call('image-to-3d',{image_url:image,ai_model:process.env.MESHY_MODEL||'meshy-7.1',should_texture:true,enable_pbr:true,should_remesh:true,target_polycount:100000,pose_mode:'a-pose',target_formats:['glb']});if(!valid(result.result))throw new Error('未返回人物任务编号');const job={id:result.result,stage:'model',task:result.result};await save(job);return {id:job.id}},
 async poll(id){if(locks.has(id))return locks.get(id);const work=(async()=>{const job=await read(id);if(job.done)return job;if(job.failed)throw new Error(job.failed);if(job.submitting)throw new Error('上一阶段的提交结果未知，请在服务商控制台核对后再重试，避免重复计费');const route={model:'image-to-3d',rig:'rigging',animation:'animations'}[job.stage];const task=await call(route+'/'+encodeURIComponent(job.task));if(['FAILED','CANCELED'].includes(task.status)){job.failed='人物'+({model:'重建',rig:'骨骼绑定',animation:'动作生成'}[job.stage])+'失败，请更换四肢完整清晰的全身照片后重试';await save(job);throw new Error(job.failed)}if(task.status!=='SUCCEEDED')return {done:false,stage:job.stage,progress:task.progress||0};
 if(job.stage==='animation'){job.model=await asset(task.result?.animation_glb_url,job.id+'-animated.glb');job.done=true;await save(job);return job}
 let payload,next;if(job.stage==='model'){payload={input_task_id:job.id,height_meters:1.7};next='rig'}else{job.actions=pickActions(await call('animations/library'));payload={rig_task_id:job.task,action_ids:job.actions.map(a=>a.id)};next='animation'}job.submitting=true;await save(job);const submitted=await call(next==='rig'?'rigging':'animations',payload);if(!valid(submitted.result))throw new Error('动作服务未返回有效任务编号');job.task=submitted.result;job.stage=next;job.submitting=false;await save(job);return {done:false,stage:next,progress:0}})();locks.set(id,work);try{return await work}finally{locks.delete(id)}}}
}
