import fs from 'node:fs';
import * as T from '../public/vendor/three.module.min.js';
import {mergeGeometries,mergeVertices} from '../public/vendor/BufferGeometryUtils.js';
const src=(process.argv[2]||'work/bmw-m4-g82').replace(/\/$/,'')+'/',g=JSON.parse(fs.readFileSync(src+'scene.gltf')),bin=fs.readFileSync(src+'scene.bin');
const types={5126:Float32Array,5123:Uint16Array,5125:Uint32Array,5121:Uint8Array},widths={SCALAR:1,VEC2:2,VEC3:3,VEC4:4};
function attribute(id){const a=g.accessors[id],v=g.bufferViews[a.bufferView],Type=types[a.componentType],width=widths[a.type],stride=v.byteStride||width*Type.BYTES_PER_ELEMENT,offset=(v.byteOffset||0)+(a.byteOffset||0),out=new Type(a.count*width);for(let i=0;i<a.count;i++)out.set(new Type(bin.buffer,bin.byteOffset+offset+i*stride,width),i*width);return new T.BufferAttribute(out,width,a.normalized);}
const parts=[],box=new T.Box3();function visit(id,parent){const n=g.nodes[id],m=new T.Matrix4();if(n.matrix)m.fromArray(n.matrix);else m.compose(new T.Vector3(...(n.translation||[0,0,0])),new T.Quaternion(...(n.rotation||[0,0,0,1])),new T.Vector3(...(n.scale||[1,1,1])));m.premultiply(parent);if(n.mesh!==undefined)for(const p of g.meshes[n.mesh].primitives){const geo=new T.BufferGeometry();for(const [key,id] of Object.entries(p.attributes))geo.setAttribute({POSITION:'position',NORMAL:'normal',TEXCOORD_0:'uv',TANGENT:'tangent'}[key],attribute(id));geo.setIndex(attribute(p.indices));geo.applyMatrix4(m);geo.computeBoundingBox();box.union(geo.boundingBox);parts.push({geo,mat:p.material,mesh:n.mesh,name:n.name});}for(const child of n.children||[])visit(child,m);}for(const id of g.scenes[g.scene].nodes)visit(id,new T.Matrix4());
const scale=4.794/(box.max.z-box.min.z),cz=(box.min.z+box.max.z)/2,normalize=new T.Matrix4().set(-scale,0,0,0,0,0,scale,-cz*scale,0,scale,0,-box.min.y*scale+.018,0,0,0,1);
// Merge exporter chunks by original named object, preserving material seams.
const groups=new Map();for(const p of parts){p.geo.applyMatrix4(normalize);const key=p.name.replace(/_\d+$/,'')+'_'+p.mat;if(!groups.has(key))groups.set(key,{name:p.name.replace(/_\d+$/,''),mat:p.mat,mesh:p.mesh,geos:[]});groups.get(key).geos.push(p.geo);}
function components(geo){const pos=geo.attributes.position,parents=Int32Array.from({length:pos.count},(_,i)=>i),weld=new Map(),find=i=>{while(parents[i]!==i){parents[i]=parents[parents[i]];i=parents[i];}return i;},join=(a,b)=>parents[find(a)]=find(b);for(let i=0;i<pos.count;i++){const k=[pos.getX(i),pos.getY(i),pos.getZ(i)].map(x=>Math.round(x*1e5)).join(',');if(weld.has(k))join(i,weld.get(k));else weld.set(k,i);}const idx=geo.index.array;for(let i=0;i<idx.length;i+=3){join(idx[i],idx[i+1]);join(idx[i],idx[i+2]);}const items=new Map();for(let i=0;i<pos.count;i++){const id=find(i);if(!items.has(id))items.set(id,{box:new T.Box3(),triangles:[]});items.get(id).box.expandByPoint(new T.Vector3().fromBufferAttribute(pos,i));}for(let i=0;i<idx.length;i+=3)items.get(find(idx[i])).triangles.push(idx[i],idx[i+1],idx[i+2]);return [...items.values()];}
const compiled=[];for(const p of groups.values()){const geo=mergeVertices(mergeGeometries(p.geos),1e-4);const cs=components(geo);compiled.push({...p,geo,components:cs,geos:undefined});}
// Repack every source triangle; named assemblies are animated by the runtime.
const dest='public/vehicles/cars/M4/';fs.mkdirSync(dest,{recursive:true});
const out={asset:{...g.asset,generator:'OpenRoad G82 preparation; geometry welded at 0.1 mm, original triangle count preserved'},scene:0,scenes:[{nodes:[]}],nodes:[],meshes:[],materials:g.materials,textures:g.textures,images:g.images,samplers:g.samplers,extensionsUsed:g.extensionsUsed,accessors:[],bufferViews:[],buffers:[]},chunks=[];let offset=0,triangles=0;
function accessor(array,width,min,max){const bytes=Buffer.from(array.buffer,array.byteOffset,array.byteLength),pad=(4-offset%4)%4;if(pad){chunks.push(Buffer.alloc(pad));offset+=pad;}const view=out.bufferViews.length;out.bufferViews.push({buffer:0,byteOffset:offset,byteLength:bytes.length});chunks.push(bytes);offset+=bytes.length;const id=out.accessors.length;out.accessors.push({bufferView:view,componentType:array instanceof Float32Array?5126:array instanceof Uint16Array?5123:5125,count:array.length/width,type:{1:'SCALAR',2:'VEC2',3:'VEC3',4:'VEC4'}[width],...(min?{min,max}:{})});return id;}
function exportMesh(geo,indices,name,mat){if(!indices.length)return;const ids=[...new Set(indices)],map=new Map(ids.map((id,i)=>[id,i])),attrs={};const bb=new T.Box3();for(const [key,attr] of Object.entries(geo.attributes)){const vals=new Float32Array(ids.length*attr.itemSize);ids.forEach((id,i)=>{for(let k=0;k<attr.itemSize;k++)vals[i*attr.itemSize+k]=attr.array[id*attr.itemSize+k];if(key==='position'||key==='normal'){const x=vals[i*3],y=vals[i*3+1],z=vals[i*3+2];vals[i*3]=-x;vals[i*3+1]=z-(key==='position'?.018:0);vals[i*3+2]=y;if(key==='position')bb.expandByPoint(new T.Vector3().fromArray(vals,i*3));}});attrs[{position:'POSITION',normal:'NORMAL',uv:'TEXCOORD_0',tangent:'TANGENT'}[key]]=accessor(vals,attr.itemSize,key==='position'?bb.min.toArray():undefined,key==='position'?bb.max.toArray():undefined);}const idx=ids.length>65535?new Uint32Array(indices.map(i=>map.get(i))):new Uint16Array(indices.map(i=>map.get(i)));const mesh=out.meshes.length;out.meshes.push({name,primitives:[{attributes:attrs,indices:accessor(idx,1),material:mat,mode:4}]});out.scenes[0].nodes.push(out.nodes.length);out.nodes.push({name,mesh});triangles+=indices.length/3;}
for(const p of compiled){const sections=new Map();for(const c of p.components){const b=c.box,steering=b.min.x>-.59&&b.max.x<-.19&&b.min.y>.30&&b.max.y<.49&&b.min.z>.72&&b.max.z<1.07;let prefix=steering?'Steering_':'Body_';if(p.name==='model_13_Material.011'&&b.min.z>.97&&b.max.z<1.24&&b.min.y>.36&&b.max.y<.51)prefix='Mirror_';if(/^model_(3_Material|3\.001|21_|22_|24_)/.test(p.name)||(p.name.startsWith('model_23_')&&Math.abs(b.getCenter(new T.Vector3()).x)>.7)){prefix=p.name.startsWith('model_24_')?'Caliper_':'Wheel_';}const name=prefix+p.name;if(!sections.has(name))sections.set(name,[]);const target=sections.get(name);for(const i of c.triangles)target.push(i);}for(const [name,idx] of sections)exportMesh(p.geo,idx,name,p.mat);}
const data=Buffer.concat(chunks);out.buffers.push({uri:'model.bin',byteLength:data.length});fs.writeFileSync(dest+'scene.gltf',JSON.stringify(out));fs.writeFileSync(dest+'model.bin',data);fs.cpSync(src+'textures',dest+'textures',{recursive:true});fs.copyFileSync(src+'license.txt',dest+'source-license.txt');console.log('EXPORTED',data.length,'bytes',triangles,'triangles',out.meshes.length,'meshes');if(triangles!==parts.reduce((sum,p)=>sum+p.geo.index.count/3,0))throw Error('Triangle count changed');
